name: food_tracker
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.4.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  barcode_scan2: ^4.3.3
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.4
  http: ^0.13.4
  openfoodfacts: ^3.12.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  uuid: ^4.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
